// <auto-generated />
namespace DataProvider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v123));
        
        string IMigrationMetadata.Id
        {
            get { return "202107182047398_v123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
